#!/usr/bin/env pwsh
#Requires -Version 7.0
<#
.SYNOPSIS
    Deploy infrastructure for the .NET Agent Framework workshop (Lab 1).

.DESCRIPTION
    Mirrors the CI/CD workflow: unlocks state storage, runs terraform
    init/validate/plan/apply, then shows next steps.

    Reads resource group / storage account names from the terraform.tfvars
    and backend.hcl generated by init.ps1.

.EXAMPLE
    ./deploy.ps1
#>

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

$ScriptDir    = $PSScriptRoot
$TerraformDir = "$ScriptDir\terraform"

# ── Helpers ──────────────────────────────────────────────────────────────────
function Write-Banner {
    Write-Host ""
    Write-Host "  ╔═══════════════════════════════════════════════════════╗" -ForegroundColor DarkCyan
    Write-Host "  ║                                                       ║" -ForegroundColor DarkCyan
    Write-Host "  ║   .NET Agent Framework — Lab 1 Deploy                 ║" -ForegroundColor DarkCyan
    Write-Host "  ║                                                       ║" -ForegroundColor DarkCyan
    Write-Host "  ║   This script deploys all Azure infrastructure:       ║" -ForegroundColor DarkCyan
    Write-Host "  ║     1. Unlock state storage                           ║" -ForegroundColor DarkCyan
    Write-Host "  ║     2. terraform init                                 ║" -ForegroundColor DarkCyan
    Write-Host "  ║     3. terraform validate                             ║" -ForegroundColor DarkCyan
    Write-Host "  ║     4. terraform plan                                 ║" -ForegroundColor DarkCyan
    Write-Host "  ║     5. terraform apply                                ║" -ForegroundColor DarkCyan
    Write-Host "  ║     6. Seed CRM data                                  ║" -ForegroundColor DarkCyan
    Write-Host "  ║                                                       ║" -ForegroundColor DarkCyan
    Write-Host "  ╚═══════════════════════════════════════════════════════╝" -ForegroundColor DarkCyan
    Write-Host ""
}

function Write-Phase {
    param([int]$Number, [string]$Title)
    Write-Host ""
    Write-Host "  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━" -ForegroundColor DarkGray
    Write-Host "  Phase $Number — $Title" -ForegroundColor Cyan
    Write-Host "  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━" -ForegroundColor DarkGray
}

function Write-Step  { param([string]$Message) Write-Host "  → $Message" -ForegroundColor White }
function Write-Done  { param([string]$Message) Write-Host "    ✓ $Message" -ForegroundColor Green }

function Write-PhaseSummary {
    param([int]$Number, [hashtable]$Items, [string]$NextPhase)
    
    # Build content lines and find max width
    $header = " Phase $Number complete "
    $lines = @()
    foreach ($kv in $Items.GetEnumerator()) {
        $lines += "  $($kv.Key): $($kv.Value)"
    }
    $maxLen = ($lines | ForEach-Object { $_.Length }) | Measure-Object -Maximum | Select-Object -ExpandProperty Maximum
    $maxLen = [Math]::Max($maxLen, $header.Length)
    $boxWidth = $maxLen + 2  # padding

    $topFill = '─' * ($boxWidth - $header.Length)
    $botFill = '─' * $boxWidth

    Write-Host ""
    Write-Host "    ┌${header}${topFill}┐" -ForegroundColor Green
    foreach ($line in $lines) {
        $pad = ' ' * ($boxWidth - $line.Length)
        Write-Host "    │" -ForegroundColor Green -NoNewLine
        Write-Host "${line}${pad}" -NoNewLine
        Write-Host "│" -ForegroundColor Green
    }
    Write-Host "    └${botFill}┘" -ForegroundColor Green
    if ($NextPhase) {
        Write-Host "    Next: " -NoNewLine -ForegroundColor DarkGray
        Write-Host "$NextPhase" -ForegroundColor Cyan
    }
    $response = Read-Host "    Continue? (Y/n)"
    if ($response -eq 'n' -or $response -eq 'N') {
        Write-Host "    Stopped by user." -ForegroundColor Yellow
        exit 0
    }
}

function Read-HclValue {
    param([string]$FilePath, [string]$Key)
    $line = Get-Content $FilePath | Where-Object { $_ -match "^\s*$Key\s*=" } | Select-Object -First 1
    if ($line -match '=\s*"([^"]*)"') { return $Matches[1] }
    return $null
}

# ── Select environment ───────────────────────────────────────────────────────────

$TfVarsFiles = @(Get-ChildItem -Path $TerraformDir -Filter "*.tfvars" | Where-Object { $_.Name -ne 'example.tfvars' })

if ($TfVarsFiles.Count -eq 0) {
    throw "No .tfvars files found in $TerraformDir — run init.ps1 first."
}

Write-Banner

# ── Azure login ───────────────────────────────────────────────────────────────
Write-Host "    Signing in to Azure — select the correct account in the browser." -ForegroundColor DarkGray
Write-Host ""
az login | Out-Null

if ($TfVarsFiles.Count -eq 1) {
    $Environment = $TfVarsFiles[0].BaseName
    Write-Host "    Found environment: " -NoNewLine; Write-Host "$Environment" -ForegroundColor Cyan
} else {
    Write-Host "    Available environments:" -ForegroundColor DarkGray
    Write-Host ""
    for ($i = 0; $i -lt $TfVarsFiles.Count; $i++) {
        Write-Host "      $($i + 1). $($TfVarsFiles[$i].BaseName)" -ForegroundColor Cyan
    }
    Write-Host ""
    $pick = Read-Host "    Select environment [1-$($TfVarsFiles.Count)]"
    if ($pick -match '^\d+$') {
        $idx = [int]$pick - 1
        if ($idx -ge 0 -and $idx -lt $TfVarsFiles.Count) {
            $Environment = $TfVarsFiles[$idx].BaseName
        } else {
            throw "Invalid selection: $pick"
        }
    } else {
        throw "Invalid selection: $pick"
    }
}

# ── Read config ──────────────────────────────────────────────────────────────────

$TfVarsFile  = "$TerraformDir\$Environment.tfvars"
$BackendFile = "$TerraformDir\backend.hcl"

if (-not (Test-Path $BackendFile)) { throw "backend.hcl not found — run init.ps1 first." }

$ResourceGroup  = Read-HclValue -FilePath $TfVarsFile -Key "resource_group_name"
$Location       = Read-HclValue -FilePath $TfVarsFile -Key "location"
$StorageAccount = Read-HclValue -FilePath $BackendFile -Key "storage_account_name"

if (-not $ResourceGroup -or -not $StorageAccount -or -not $Environment) {
    throw "Could not read required values from config files. Re-run init.ps1."
}

Write-Host ""
Write-Host "    Environment:     " -NoNewLine; Write-Host "$Environment" -ForegroundColor Cyan
Write-Host "    Resource group:  " -NoNewLine; Write-Host "$ResourceGroup" -ForegroundColor Cyan
Write-Host "    Storage account: " -NoNewLine; Write-Host "$StorageAccount" -ForegroundColor Cyan
Write-Host "    Location:        " -NoNewLine; Write-Host "$Location" -ForegroundColor Cyan
Write-Host ""

# ═══════════════════════════════════════════════════════════════════════════════
# PHASE 1 — Unlock state storage
# ═══════════════════════════════════════════════════════════════════════════════

Write-Phase -Number 1 -Title "Unlock state storage"

Write-Step "Enabling public access on $StorageAccount"

az storage account update `
    --name $StorageAccount `
    --resource-group $ResourceGroup `
    --public-network-access Enabled | Out-Null

Write-Done "Public access enabled on $StorageAccount"

Write-PhaseSummary -Number 1 -NextPhase "Phase 2 — terraform init (configure backend)" -Items ([ordered]@{
    "Storage account" = $StorageAccount
    "Public access"   = "Enabled"
})

# ═══════════════════════════════════════════════════════════════════════════════
# PHASE 2 — terraform init
# ═══════════════════════════════════════════════════════════════════════════════

Write-Phase -Number 2 -Title "terraform init"

Write-Step "Initializing Terraform with backend config"

Push-Location $TerraformDir
try {
    cmd /c "terraform init -upgrade -reconfigure -backend-config=backend.hcl"
    if ($LASTEXITCODE -ne 0) { throw "terraform init failed" }
    Write-Done "Terraform initialized"
} finally {
    Pop-Location
}

Write-PhaseSummary -Number 2 -NextPhase "Phase 3 — terraform validate (check configuration syntax)" -Items ([ordered]@{
    "Backend" = "azurerm ($StorageAccount/tfstate/$Environment.tfstate)"
    "Status"  = "Initialized"
})

# ═══════════════════════════════════════════════════════════════════════════════
# PHASE 3 — terraform validate
# ═══════════════════════════════════════════════════════════════════════════════

Write-Phase -Number 3 -Title "terraform validate"

Write-Step "Validating Terraform configuration"

Push-Location $TerraformDir
try {
    terraform validate
    if ($LASTEXITCODE -ne 0) { throw "terraform validate failed — fix errors above and re-run" }
    Write-Done "Configuration is valid"
} finally {
    Pop-Location
}

Write-PhaseSummary -Number 3 -NextPhase "Phase 4 — terraform plan (preview infrastructure changes)" -Items ([ordered]@{
    "Status" = "Valid"
})

# ═══════════════════════════════════════════════════════════════════════════════
# PHASE 4 — terraform plan
# ═══════════════════════════════════════════════════════════════════════════════

Write-Phase -Number 4 -Title "terraform plan"

Write-Step "Planning infrastructure changes"

Push-Location $TerraformDir
try {
    cmd /c "terraform plan -var-file=$Environment.tfvars -out=tfplan"
    if ($LASTEXITCODE -ne 0) { throw "terraform plan failed" }
    Write-Done "Plan saved to tfplan"
} finally {
    Pop-Location
}

Write-PhaseSummary -Number 4 -NextPhase "Phase 5 — terraform apply (provision all resources)" -Items ([ordered]@{
    "Plan file" = "tfplan"
    "Status"    = "Ready to apply"
})

# ═══════════════════════════════════════════════════════════════════════════════
# PHASE 5 — terraform apply
# ═══════════════════════════════════════════════════════════════════════════════

Write-Phase -Number 5 -Title "terraform apply"

Write-Step "Applying infrastructure changes"
Write-Host "    Resources: AI Foundry, SQL, Cosmos DB, AI Search, AKS, ACR, Key Vault, Storage" -ForegroundColor DarkGray
Write-Host ""

Push-Location $TerraformDir
try {
    terraform apply "tfplan"
    if ($LASTEXITCODE -ne 0) { throw "terraform apply failed" }
    Write-Done "All resources deployed"
} finally {
    Pop-Location
}

# ── Clean up ─────────────────────────────────────────────────────────────────
if (Test-Path "$TerraformDir\tfplan") {
    Remove-Item "$TerraformDir\tfplan" -Force
}

Write-PhaseSummary -Number 5 -NextPhase "Phase 6 — Seed CRM data into Azure SQL Database" -Items ([ordered]@{
    "Status" = "Applied successfully"
})

# ═══════════════════════════════════════════════════════════════════════════════
# PHASE 6 — Seed CRM data
# ═══════════════════════════════════════════════════════════════════════════════

Write-Phase -Number 6 -Title "Seed CRM data"

Write-Step "Discovering Key Vault in $ResourceGroup"
$KvName = az keyvault list --resource-group $ResourceGroup --query "[0].name" -o tsv
if (-not $KvName) { throw "No Key Vault found in $ResourceGroup" }
Write-Done "Key Vault: $KvName"

Write-Step "Reading SQL credentials from Key Vault"
$SqlFqdn  = az keyvault secret show --vault-name $KvName --name "SQL-SERVER-FQDN" --query value -o tsv
$SqlDb    = az keyvault secret show --vault-name $KvName --name "SQL-DATABASE-NAME" --query value -o tsv
$SqlLogin = az keyvault secret show --vault-name $KvName --name "SQL-ADMIN-LOGIN" --query value -o tsv
$SqlPass  = az keyvault secret show --vault-name $KvName --name "SQL-ADMIN-PASSWORD" --query value -o tsv
Write-Done "SQL Server: $SqlFqdn / $SqlDb"

Write-Step "Running seed-data tool"

$SeedDataDir = Join-Path (Split-Path $ScriptDir) "src" "seed-data"
Push-Location $SeedDataDir
try {
    $env:SQL_SERVER_FQDN    = $SqlFqdn
    $env:SQL_DATABASE_NAME  = $SqlDb
    $env:SQL_ADMIN_LOGIN    = $SqlLogin
    $env:SQL_ADMIN_PASSWORD = $SqlPass
    dotnet run
    if ($LASTEXITCODE -ne 0) { throw "seed-data failed" }
    Write-Done "CRM data seeded"
} finally {
    Remove-Item Env:\SQL_SERVER_FQDN, Env:\SQL_DATABASE_NAME, Env:\SQL_ADMIN_LOGIN, Env:\SQL_ADMIN_PASSWORD -ErrorAction SilentlyContinue
    Pop-Location
}

Write-PhaseSummary -Number 6 -NextPhase "Phase 7 — Link Entra users to Customers table" -Items ([ordered]@{
    "Status" = "CRM data seeded"
})

# ═══════════════════════════════════════════════════════════════════════════════
# PHASE 7 — Link Entra user object IDs to Customers table
# ═══════════════════════════════════════════════════════════════════════════════

Write-Phase -Number 7 -Title "Link Entra users to Customers"

Write-Step "Reading Entra object IDs from Key Vault"

$CustomerMapping = @(
    @{ CustomerId = "101"; SecretName = "CUSTOMER-EMMA-ENTRA-OID";  Name = "Emma Wilson" }
    @{ CustomerId = "102"; SecretName = "CUSTOMER-JAMES-ENTRA-OID"; Name = "James Chen" }
    @{ CustomerId = "103"; SecretName = "CUSTOMER-SARAH-ENTRA-OID"; Name = "Sarah Miller" }
    @{ CustomerId = "104"; SecretName = "CUSTOMER-DAVID-ENTRA-OID"; Name = "David Park" }
    @{ CustomerId = "105"; SecretName = "CUSTOMER-LISA-ENTRA-OID";  Name = "Lisa Torres" }
)

$ConnStr = "Server=tcp:${SqlFqdn},1433;Database=${SqlDb};User ID=${SqlLogin};Password=${SqlPass};Encrypt=True;TrustServerCertificate=False;"

foreach ($mapping in $CustomerMapping) {
    $oid = az keyvault secret show --vault-name $KvName --name $mapping.SecretName --query value -o tsv
    if ($oid) {
        $sql = "UPDATE Customers SET entra_id = @oid WHERE id = @cid"
        Invoke-Sqlcmd -ConnectionString $ConnStr -Query $sql -Variable "oid=$oid", "cid=$($mapping.CustomerId)" -ErrorAction SilentlyContinue 2>$null
        if (-not $?) {
            # Fallback: use sqlcmd command-line tool
            sqlcmd -S "tcp:${SqlFqdn},1433" -d $SqlDb -U $SqlLogin -P $SqlPass -Q "UPDATE Customers SET entra_id = '$oid' WHERE id = '$($mapping.CustomerId)'" 2>$null
        }
        Write-Done "$($mapping.Name) (ID $($mapping.CustomerId)) → $($oid.Substring(0,8))..."
    } else {
        Write-Host "    ⚠ Could not read $($mapping.SecretName) from Key Vault" -ForegroundColor Yellow
    }
}

# ── Read Key Vault URI ────────────────────────────────────────────────────────
$KeyVaultUri = (az keyvault show --name $KvName --query properties.vaultUri -o tsv 2>$null)

# ── Final summary ────────────────────────────────────────────────────────────
Write-Host ""
Write-Host "  ╔═══════════════════════════════════════════════════════╗" -ForegroundColor Green
Write-Host "  ║  Deployment Complete!                                 ║" -ForegroundColor Green
Write-Host "  ╠═══════════════════════════════════════════════════════╣" -ForegroundColor Green
Write-Host "  ║" -ForegroundColor Green -NoNewLine; Write-Host "  Environment:    $Environment"
Write-Host "  ║" -ForegroundColor Green -NoNewLine; Write-Host "  Resource group: $ResourceGroup"
Write-Host "  ║" -ForegroundColor Green -NoNewLine; Write-Host "  Location:       $Location"
if ($KeyVaultUri) {
    Write-Host "  ║" -ForegroundColor Green -NoNewLine; Write-Host "  Key Vault URI:  $KeyVaultUri"
}
Write-Host "  ║" -ForegroundColor Green
Write-Host "  ║  Next steps:                                          " -ForegroundColor Green
Write-Host "  ║    1. cd src/config-sync                               " -ForegroundColor Green
Write-Host "  ║    2. dotnet run -- $KeyVaultUri" -ForegroundColor Green
Write-Host "  ║    3. cd ../simple-agent && dotnet run                 " -ForegroundColor Green
Write-Host "  ╚═══════════════════════════════════════════════════════╝" -ForegroundColor Green
Write-Host ""
