#!/usr/bin/env pwsh
#Requires -Version 7.0
<#
.SYNOPSIS
    Deploy infrastructure for the .NET Agent Framework workshop (Lab 1).

.DESCRIPTION
    Mirrors the CI/CD workflow: unlocks state storage, runs terraform
    init/validate/plan/apply, then shows next steps.

    Reads resource group / storage account names from the terraform.tfvars
    and backend.hcl generated by init.ps1.

.EXAMPLE
    ./deploy.ps1
#>

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

$ScriptDir    = $PSScriptRoot
$TerraformDir = "$ScriptDir\terraform"

# ── Helpers ──────────────────────────────────────────────────────────────────
function Write-Banner {
    Write-Host ""
    Write-Host "  ╔═══════════════════════════════════════════════════════╗" -ForegroundColor DarkCyan
    Write-Host "  ║                                                       ║" -ForegroundColor DarkCyan
    Write-Host "  ║   .NET Agent Framework — Lab 1 Deploy                 ║" -ForegroundColor DarkCyan
    Write-Host "  ║                                                       ║" -ForegroundColor DarkCyan
    Write-Host "  ║   This script deploys all Azure infrastructure:       ║" -ForegroundColor DarkCyan
    Write-Host "  ║     1. Unlock state storage                           ║" -ForegroundColor DarkCyan
    Write-Host "  ║     2. terraform init                                 ║" -ForegroundColor DarkCyan
    Write-Host "  ║     3. terraform validate                             ║" -ForegroundColor DarkCyan
    Write-Host "  ║     4. terraform plan                                 ║" -ForegroundColor DarkCyan
    Write-Host "  ║     5. terraform apply                                ║" -ForegroundColor DarkCyan
    Write-Host "  ║     6. Seed CRM data                                  ║" -ForegroundColor DarkCyan
    Write-Host "  ║     7. Link Entra users to Customers                  ║" -ForegroundColor DarkCyan
    Write-Host "  ║                                                       ║" -ForegroundColor DarkCyan
    Write-Host "  ╚═══════════════════════════════════════════════════════╝" -ForegroundColor DarkCyan
    Write-Host ""
}

function Write-Phase {
    param([int]$Number, [string]$Title)
    Write-Host ""
    Write-Host "  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━" -ForegroundColor DarkGray
    Write-Host "  Phase $Number — $Title" -ForegroundColor Cyan
    Write-Host "  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━" -ForegroundColor DarkGray
}

function Write-Step  { param([string]$Message) Write-Host "  → $Message" -ForegroundColor White }
function Write-Done  { param([string]$Message) Write-Host "    ✓ $Message" -ForegroundColor Green }

function Write-PhaseSummary {
    param([int]$Number, [hashtable]$Items, [string]$NextPhase)
    
    # Build content lines and find max width
    $header = " Phase $Number complete "
    $lines = @()
    foreach ($kv in $Items.GetEnumerator()) {
        $lines += "  $($kv.Key): $($kv.Value)"
    }
    $maxLen = ($lines | ForEach-Object { $_.Length }) | Measure-Object -Maximum | Select-Object -ExpandProperty Maximum
    $maxLen = [Math]::Max($maxLen, $header.Length)
    $boxWidth = $maxLen + 2  # padding

    $topFill = '─' * ($boxWidth - $header.Length)
    $botFill = '─' * $boxWidth

    Write-Host ""
    Write-Host "    ┌${header}${topFill}┐" -ForegroundColor Green
    foreach ($line in $lines) {
        $pad = ' ' * ($boxWidth - $line.Length)
        Write-Host "    │" -ForegroundColor Green -NoNewLine
        Write-Host "${line}${pad}" -NoNewLine
        Write-Host "│" -ForegroundColor Green
    }
    Write-Host "    └${botFill}┘" -ForegroundColor Green
    if ($NextPhase) {
        Write-Host "    Next: " -NoNewLine -ForegroundColor DarkGray
        Write-Host "$NextPhase" -ForegroundColor Cyan
    }
    $response = Read-Host "    Continue? (Y/n)"
    if ($response -eq 'n' -or $response -eq 'N') {
        Write-Host "    Stopped by user." -ForegroundColor Yellow
        exit 0
    }
}

function Read-HclValue {
    param([string]$FilePath, [string]$Key)
    $line = Get-Content $FilePath | Where-Object { $_ -match "^\s*$Key\s*=" } | Select-Object -First 1
    if ($line -match '=\s*"([^"]*)"') { return $Matches[1] }
    return $null
}

function Add-DeployerFirewallRules {
    param([string]$ResourceGroup, [string]$DeployerIp)
    Write-Host ""
    Write-Host "  ━━ Adding deployer IP $DeployerIp to resource firewalls ━━" -ForegroundColor Yellow

    # Key Vault
    Write-Host "    Key Vaults..." -ForegroundColor DarkGray -NoNewline
    $kvNames = az keyvault list --resource-group $ResourceGroup --query "[].name" -o tsv 2>$null
    foreach ($kv in ($kvNames -split "`n" | Where-Object { $_ })) {
        az keyvault network-rule add --name $kv.Trim() --ip-address "$DeployerIp/32" 2>$null | Out-Null
    }
    Write-Host " done" -ForegroundColor DarkGray

    # Storage accounts (excluding state storage — handled separately)
    Write-Host "    Storage accounts..." -ForegroundColor DarkGray -NoNewline
    $stNames = az storage account list --resource-group $ResourceGroup --query "[].name" -o tsv 2>$null
    foreach ($st in ($stNames -split "`n" | Where-Object { $_ })) {
        az storage account network-rule add --resource-group $ResourceGroup --account-name $st.Trim() --ip-address $DeployerIp 2>$null | Out-Null
    }
    Write-Host " done" -ForegroundColor DarkGray

    # Cosmos DB (--no-wait: the ARM operation is slow but the firewall rule takes effect immediately)
    Write-Host "    Cosmos DB..." -ForegroundColor DarkGray -NoNewline
    $cosmosNames = az cosmosdb list --resource-group $ResourceGroup --query "[].name" -o tsv 2>$null
    foreach ($c in ($cosmosNames -split "`n" | Where-Object { $_ })) {
        $c = $c.Trim()
        $existing = az cosmosdb show --name $c --resource-group $ResourceGroup --query "ipRules[].ipAddressOrRange" -o tsv 2>$null
        $alreadyPresent = ($existing -split "`n" | Where-Object { $_.Trim() -eq $DeployerIp })
        if (-not $alreadyPresent) {
            $newIps = @($existing -split "`n" | Where-Object { $_ }) + @($DeployerIp)
            $ipFilter = ($newIps | ForEach-Object { $_.Trim() } | Where-Object { $_ }) -join ","
            az cosmosdb update --name $c --resource-group $ResourceGroup --ip-range-filter $ipFilter --no-wait 2>$null | Out-Null
        }
    }
    Write-Host " done" -ForegroundColor DarkGray

    # Cognitive Services
    Write-Host "    Cognitive Services..." -ForegroundColor DarkGray -NoNewline
    $cogNames = az cognitiveservices account list --resource-group $ResourceGroup --query "[].name" -o tsv 2>$null
    foreach ($cog in ($cogNames -split "`n" | Where-Object { $_ })) {
        az cognitiveservices account network-rule add --resource-group $ResourceGroup --name $cog.Trim() --ip-address "$DeployerIp/32" 2>$null | Out-Null
    }
    Write-Host " done" -ForegroundColor DarkGray

    # AI Search
    Write-Host "    AI Search..." -ForegroundColor DarkGray -NoNewline
    $searchNames = az search service list --resource-group $ResourceGroup --query "[].name" -o tsv 2>$null
    foreach ($s in ($searchNames -split "`n" | Where-Object { $_ })) {
        $s = $s.Trim()
        $currentIps = az search service show --name $s --resource-group $ResourceGroup --query "networkRuleSet.ipRules[].value" -o tsv 2>$null
        $alreadyPresent = ($currentIps -split "`n" | Where-Object { $_.Trim() -eq $DeployerIp })
        if (-not $alreadyPresent) {
            $newRules = @($currentIps -split "`n" | Where-Object { $_ } | ForEach-Object { @{value=$_.Trim()} }) + @(@{value=$DeployerIp})
            $ipRules = ConvertTo-Json -InputObject $newRules -Compress
            az search service update --name $s --resource-group $ResourceGroup --ip-rules $ipRules 2>$null | Out-Null
        }
    }
    Write-Host " done" -ForegroundColor DarkGray

    Write-Host "  ━━ Deployer IP added to all resource firewalls ━━" -ForegroundColor Green
}

function Remove-DeployerFirewallRules {
    param([string]$ResourceGroup, [string]$DeployerIp)
    Write-Host ""
    Write-Host "  ━━ Removing deployer IP $DeployerIp from all firewalls (always runs) ━━" -ForegroundColor Yellow

    # Key Vault
    Write-Host "    Key Vaults..." -ForegroundColor DarkGray -NoNewline
    $kvNames = az keyvault list --resource-group $ResourceGroup --query "[].name" -o tsv 2>$null
    foreach ($kv in ($kvNames -split "`n" | Where-Object { $_ })) {
        az keyvault network-rule remove --name $kv.Trim() --ip-address "$DeployerIp/32" 2>$null | Out-Null
    }
    Write-Host " done" -ForegroundColor DarkGray

    # Storage accounts
    Write-Host "    Storage accounts..." -ForegroundColor DarkGray -NoNewline
    $stNames = az storage account list --resource-group $ResourceGroup --query "[].name" -o tsv 2>$null
    foreach ($st in ($stNames -split "`n" | Where-Object { $_ })) {
        az storage account network-rule remove --resource-group $ResourceGroup --account-name $st.Trim() --ip-address $DeployerIp 2>$null | Out-Null
    }
    Write-Host " done" -ForegroundColor DarkGray

    # Cosmos DB (--no-wait: the ARM operation is slow but the firewall rule takes effect immediately)
    Write-Host "    Cosmos DB..." -ForegroundColor DarkGray -NoNewline
    $cosmosNames = az cosmosdb list --resource-group $ResourceGroup --query "[].name" -o tsv 2>$null
    foreach ($c in ($cosmosNames -split "`n" | Where-Object { $_ })) {
        $c = $c.Trim()
        $existing = az cosmosdb show --name $c --resource-group $ResourceGroup --query "ipRules[].ipAddressOrRange" -o tsv 2>$null
        $filtered = ($existing -split "`n" | Where-Object { $_ -and $_.Trim() -ne $DeployerIp }) -join ","
        az cosmosdb update --name $c --resource-group $ResourceGroup --ip-range-filter $filtered --no-wait 2>$null | Out-Null
    }
    Write-Host " done" -ForegroundColor DarkGray

    # Cognitive Services
    Write-Host "    Cognitive Services..." -ForegroundColor DarkGray -NoNewline
    $cogNames = az cognitiveservices account list --resource-group $ResourceGroup --query "[].name" -o tsv 2>$null
    foreach ($cog in ($cogNames -split "`n" | Where-Object { $_ })) {
        az cognitiveservices account network-rule remove --resource-group $ResourceGroup --name $cog.Trim() --ip-address "$DeployerIp/32" 2>$null | Out-Null
    }
    Write-Host " done" -ForegroundColor DarkGray

    # AI Search
    Write-Host "    AI Search..." -ForegroundColor DarkGray -NoNewline
    $searchNames = az search service list --resource-group $ResourceGroup --query "[].name" -o tsv 2>$null
    foreach ($s in ($searchNames -split "`n" | Where-Object { $_ })) {
        $s = $s.Trim()
        $currentIps = az search service show --name $s --resource-group $ResourceGroup --query "networkRuleSet.ipRules[].value" -o tsv 2>$null
        $filtered = @($currentIps -split "`n" | Where-Object { $_ -and $_.Trim() -ne $DeployerIp })
        $ipRules = if ($filtered.Count -gt 0) { (ConvertTo-Json -InputObject @($filtered | ForEach-Object { @{value=$_.Trim()} }) -Compress) } else { "[]" }
        az search service update --name $s --resource-group $ResourceGroup --ip-rules $ipRules 2>$null | Out-Null
    }
    Write-Host " done" -ForegroundColor DarkGray

    Write-Host "  ━━ Deployer IP removed from all firewalls ━━" -ForegroundColor Green
}

# ── Select environment ───────────────────────────────────────────────────────────

$TfVarsFiles = @(Get-ChildItem -Path $TerraformDir -Filter "*.tfvars" | Where-Object { $_.Name -ne 'example.tfvars' })

if ($TfVarsFiles.Count -eq 0) {
    throw "No .tfvars files found in $TerraformDir — run init.ps1 first."
}

Write-Banner

# ── Azure login ───────────────────────────────────────────────────────────────
az config set core.enable_broker_on_windows=false 2>$null
az config set core.login_experience_v2=off 2>$null
Write-Host "    Signing in to Azure — select the correct account in the browser." -ForegroundColor DarkGray
Write-Host ""
# Request Graph scope upfront to avoid stale-token errors during Key Vault reads.
az login --scope https://graph.microsoft.com/.default | Out-Null

if ($TfVarsFiles.Count -eq 1) {
    $Environment = $TfVarsFiles[0].BaseName
    Write-Host "    Found environment: " -NoNewLine; Write-Host "$Environment" -ForegroundColor Cyan
} else {
    Write-Host "    Available environments:" -ForegroundColor DarkGray
    Write-Host ""
    for ($i = 0; $i -lt $TfVarsFiles.Count; $i++) {
        Write-Host "      $($i + 1). $($TfVarsFiles[$i].BaseName)" -ForegroundColor Cyan
    }
    Write-Host ""
    $pick = Read-Host "    Select environment [1-$($TfVarsFiles.Count)]"
    if ($pick -match '^\d+$') {
        $idx = [int]$pick - 1
        if ($idx -ge 0 -and $idx -lt $TfVarsFiles.Count) {
            $Environment = $TfVarsFiles[$idx].BaseName
        } else {
            throw "Invalid selection: $pick"
        }
    } else {
        throw "Invalid selection: $pick"
    }
}

# ── Read config ──────────────────────────────────────────────────────────────────

$TfVarsFile  = "$TerraformDir\$Environment.tfvars"
$BackendFile = "$TerraformDir\backend.hcl"

if (-not (Test-Path $BackendFile)) { throw "backend.hcl not found — run init.ps1 first." }

$ResourceGroup  = Read-HclValue -FilePath $TfVarsFile -Key "resource_group_name"
$Location       = Read-HclValue -FilePath $TfVarsFile -Key "location"
$StorageAccount = Read-HclValue -FilePath $BackendFile -Key "storage_account_name"

if (-not $ResourceGroup -or -not $StorageAccount -or -not $Environment) {
    throw "Could not read required values from config files. Re-run init.ps1."
}

Write-Host ""
Write-Host "    Environment:     " -NoNewLine; Write-Host "$Environment" -ForegroundColor Cyan
Write-Host "    Resource group:  " -NoNewLine; Write-Host "$ResourceGroup" -ForegroundColor Cyan
Write-Host "    Storage account: " -NoNewLine; Write-Host "$StorageAccount" -ForegroundColor Cyan
Write-Host "    Location:        " -NoNewLine; Write-Host "$Location" -ForegroundColor Cyan
Write-Host ""

# ── Get deployer IP ──────────────────────────────────────────────────────────
$DeployerIp = (Invoke-RestMethod -Uri "https://api.ipify.org" -TimeoutSec 10).Trim()
Write-Host "    Deployer IP:     " -NoNewLine; Write-Host "$DeployerIp" -ForegroundColor Cyan
Write-Host ""

try {

# ═══════════════════════════════════════════════════════════════════════════════
# PRE-FLIGHT — Purge soft-deleted resources from previous runs
# Azure keeps deleted Key Vaults, Cognitive Services, and other resources in a
# soft-deleted state. These block re-creation with the same name. Purge them
# as a fail-safe before Terraform runs.
# ═══════════════════════════════════════════════════════════════════════════════

Write-Step "Checking for soft-deleted Cognitive Services accounts"
$softDeletedCog = az cognitiveservices account list-deleted --query "[?contains(id, '$ResourceGroup')].[name]" -o tsv 2>$null
if ($softDeletedCog) {
    foreach ($acctName in $softDeletedCog -split "`n") {
        $acctName = $acctName.Trim()
        if ($acctName) {
            Write-Host "    Purging soft-deleted account: $acctName" -ForegroundColor Yellow
            az cognitiveservices account purge --location $Location --resource-group $ResourceGroup --name $acctName 2>$null
            Write-Done "Purged $acctName"
        }
    }
} else {
    Write-Done "No soft-deleted Cognitive Services accounts found"
}

Write-Step "Checking for soft-deleted Key Vaults"
$softDeletedKv = az keyvault list-deleted --query "[?properties.vaultId && contains(properties.vaultId, '$ResourceGroup')].[name]" -o tsv 2>$null
if ($softDeletedKv) {
    foreach ($kvName in $softDeletedKv -split "`n") {
        $kvName = $kvName.Trim()
        if ($kvName) {
            Write-Host "    Purging soft-deleted Key Vault: $kvName" -ForegroundColor Yellow
            az keyvault purge --name $kvName --no-wait 2>$null
            Write-Done "Purged $kvName (async)"
        }
    }
} else {
    Write-Done "No soft-deleted Key Vaults found"
}

# ═══════════════════════════════════════════════════════════════════════════════
# PHASE 1 — Unlock state storage
# ═══════════════════════════════════════════════════════════════════════════════

Write-Phase -Number 1 -Title "Unlock state storage"

Write-Step "Adding deployer IP to $StorageAccount firewall"

az storage account network-rule add `
    --account-name $StorageAccount `
    --resource-group $ResourceGroup `
    --ip-address $DeployerIp 2>$null | Out-Null

Write-Host "    Waiting 30s for firewall change to propagate..." -ForegroundColor DarkGray
Start-Sleep -Seconds 30
Write-Done "Deployer IP added to $StorageAccount"

Write-PhaseSummary -Number 1 -NextPhase "Phase 2 — terraform init (configure backend)" -Items ([ordered]@{
    "Storage account" = $StorageAccount
    "Deployer IP"     = $DeployerIp
})

# ═══════════════════════════════════════════════════════════════════════════════
# PHASE 2 — terraform init
# ═══════════════════════════════════════════════════════════════════════════════

Write-Phase -Number 2 -Title "terraform init"

Write-Step "Initializing Terraform with backend config"

Push-Location $TerraformDir
try {
    cmd /c "terraform init -upgrade -reconfigure -backend-config=backend.hcl"
    if ($LASTEXITCODE -ne 0) { throw "terraform init failed" }
    Write-Done "Terraform initialized"
} finally {
    Pop-Location
}

# ── Import existing Entra users into state (idempotent) ──────────────────────
Write-Step "Importing existing Entra users into Terraform state (if needed)"
$domain = az ad signed-in-user show --query userPrincipalName -o tsv 2>$null | ForEach-Object { $_ -replace '^[^@]+@', '' }
$userMap = @{
    emma  = "emma.wilson"
    james = "james.chen"
    sarah = "sarah.miller"
    david = "david.park"
    lisa  = "lisa.torres"
}

Push-Location $TerraformDir
try {
    foreach ($key in $userMap.Keys) {
        $upn = "$($userMap[$key])@$domain"
        # Check if already in state
        $inState = terraform state list "module.entra.azuread_user.test[`"$key`"]" 2>$null
        if (-not $inState) {
            $oid = az ad user show --id $upn --query id -o tsv 2>$null
            if ($oid) {
                Write-Host "    Importing $upn → state" -ForegroundColor DarkGray
                terraform import "module.entra.azuread_user.test[`"$key`"]" $oid 2>$null | Out-Null
            }
        }
    }
    Write-Done "Entra users synced with state"
} finally {
    Pop-Location
}

Write-PhaseSummary -Number 2 -NextPhase "Phase 3 — terraform validate (check configuration syntax)" -Items ([ordered]@{
    "Backend" = "azurerm ($StorageAccount/tfstate/$Environment.tfstate)"
    "Status"  = "Initialized"
})

# ═══════════════════════════════════════════════════════════════════════════════
# PHASE 3 — terraform validate
# ═══════════════════════════════════════════════════════════════════════════════

Write-Phase -Number 3 -Title "terraform validate"

Write-Step "Validating Terraform configuration"

Push-Location $TerraformDir
try {
    terraform validate
    if ($LASTEXITCODE -ne 0) { throw "terraform validate failed — fix errors above and re-run" }
    Write-Done "Configuration is valid"
} finally {
    Pop-Location
}

Write-PhaseSummary -Number 3 -NextPhase "Phase 4 — terraform plan (preview infrastructure changes)" -Items ([ordered]@{
    "Status" = "Valid"
})

# ═══════════════════════════════════════════════════════════════════════════════
# PHASE 4 — terraform plan
# ═══════════════════════════════════════════════════════════════════════════════

Write-Phase -Number 4 -Title "terraform plan"

# Re-add deployer IP to all resource firewalls before plan. On a retry after a
# previous failed deploy, the finally block will have stripped the deployer IP from
# every firewall. Terraform plan refreshes existing resources (blobs, certs) via
# data-plane calls, so the firewalls must be open before plan runs.
Write-Step "Ensuring deployer IP is whitelisted on existing resource firewalls"
Add-DeployerFirewallRules -ResourceGroup $ResourceGroup -DeployerIp $DeployerIp
Write-Host "    Waiting 30s for firewall changes to propagate..." -ForegroundColor DarkGray
Start-Sleep -Seconds 30

Write-Step "Planning infrastructure changes"

Push-Location $TerraformDir
try {
    cmd /c "terraform plan -var-file=$Environment.tfvars -out=tfplan"
    if ($LASTEXITCODE -ne 0) { throw "terraform plan failed" }
    Write-Done "Plan saved to tfplan"
} finally {
    Pop-Location
}

Write-PhaseSummary -Number 4 -NextPhase "Phase 5 — terraform apply (provision all resources)" -Items ([ordered]@{
    "Plan file" = "tfplan"
    "Status"    = "Ready to apply"
})

# ═══════════════════════════════════════════════════════════════════════════════
# PHASE 5 — terraform apply
# ═══════════════════════════════════════════════════════════════════════════════

Write-Phase -Number 5 -Title "terraform apply"

Write-Step "Applying infrastructure changes"
Write-Host "    Resources: AI Foundry, Cosmos DB, AI Search, AKS, ACR, Key Vault, Storage" -ForegroundColor DarkGray
Write-Host ""

Push-Location $TerraformDir
try {
    terraform apply "tfplan"
    if ($LASTEXITCODE -ne 0) {
        # ── Post-failure diagnostic: list deny policies that may have caused the failure ──
        Write-Host ""
        Write-Host "    ━━ Azure Policy diagnostic ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━" -ForegroundColor Yellow
        Write-Host "    If you see RequestDisallowedByPolicy above, a deny policy" -ForegroundColor Yellow
        Write-Host "    blocked resource creation. Listing deny policies..." -ForegroundColor Yellow
        Write-Host ""

        $SubscriptionId = az account show --query id -o tsv
        $RgScope = "/subscriptions/$SubscriptionId/resourceGroups/$ResourceGroup"
        $allAssignments = @()
        $rgA = az policy assignment list --scope $RgScope -o json 2>$null | ConvertFrom-Json
        $subA = az policy assignment list -o json 2>$null | ConvertFrom-Json
        if ($rgA) { $allAssignments += $rgA }
        if ($subA) { $allAssignments += $subA }

        $seen = @{}
        foreach ($a in $allAssignments) {
            if ($seen.ContainsKey($a.id)) { continue }
            $seen[$a.id] = $true
            if ($a.enforcementMode -ne 'Default') { continue }

            $defId = $a.policyDefinitionId
            $defName = ($defId -split '/')[-1]
            $isInitiative = $defId -match 'policySetDefinitions'
            # Capture assignment-level parameter overrides
            $assignParams = if ($a.PSObject.Properties['parameters']) { $a.parameters } else { $null }

            if ($isInitiative) {
                $members = az policy set-definition show --name $defName --query "policyDefinitions[].policyDefinitionId" -o json 2>$null | ConvertFrom-Json
                if ($members) {
                    foreach ($m in $members) {
                        $mName = ($m -split '/')[-1]
                        $mDef = az policy definition show --name $mName --query "{effect:policyRule.then.effect, defaultEffect:parameters.effect.defaultValue, displayName:displayName}" -o json 2>$null | ConvertFrom-Json
                        # Resolve effective value: assignment param override > definition default > raw effect
                        $resolvedEffect = $mDef.effect
                        if ($resolvedEffect -match '\[parameters') {
                            if ($assignParams -and $assignParams.effect -and $assignParams.effect.value) {
                                $resolvedEffect = $assignParams.effect.value
                            } elseif ($mDef.defaultEffect) {
                                $resolvedEffect = $mDef.defaultEffect
                            }
                        }
                        if ($resolvedEffect -match '(?i)deny') {
                            Write-Host "    ⚠ DENY: $($mDef.displayName)" -ForegroundColor Red
                            Write-Host "      Initiative: $($a.displayName)" -ForegroundColor DarkGray
                        }
                    }
                }
            } else {
                $pDef = az policy definition show --name $defName --query "{effect:policyRule.then.effect, defaultEffect:parameters.effect.defaultValue}" -o json 2>$null | ConvertFrom-Json
                $resolvedEffect = $pDef.effect
                if ($resolvedEffect -match '\[parameters') {
                    if ($assignParams -and $assignParams.effect -and $assignParams.effect.value) {
                        $resolvedEffect = $assignParams.effect.value
                    } elseif ($pDef.defaultEffect) {
                        $resolvedEffect = $pDef.defaultEffect
                    }
                }
                if ($resolvedEffect -match '(?i)deny') {
                    Write-Host "    ⚠ DENY: $($a.displayName)" -ForegroundColor Red
                }
            }
        }

        Write-Host ""
        Write-Host "    Fix your Terraform config to comply, then re-run deploy." -ForegroundColor Yellow
        Write-Host "    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━" -ForegroundColor Yellow
        throw "terraform apply failed"
    }
    Write-Done "All resources deployed"
} finally {
    Pop-Location
}

# ── Clean up ─────────────────────────────────────────────────────────────────
if (Test-Path "$TerraformDir\tfplan") {
    Remove-Item "$TerraformDir\tfplan" -Force
}

Write-PhaseSummary -Number 5 -NextPhase "Phase 6 — Seed CRM data into Cosmos DB" -Items ([ordered]@{
    "Status" = "Applied successfully"
})

# ═══════════════════════════════════════════════════════════════════════════════
# PHASE 6 — Seed CRM data
# ═══════════════════════════════════════════════════════════════════════════════

Write-Phase -Number 6 -Title "Seed CRM data"

Write-Step "Discovering Key Vault in $ResourceGroup"
$KvName = az keyvault list --resource-group $ResourceGroup --query "[0].name" -o tsv
if (-not $KvName) { throw "No Key Vault found in $ResourceGroup" }
Write-Done "Key Vault: $KvName"

Write-Step "Reading Cosmos DB CRM connection info from Key Vault"
$CosmosEndpoint = az keyvault secret show --vault-name $KvName --name "COSMOSDB-CRM-ENDPOINT" --query value -o tsv
$CosmosKey      = az keyvault secret show --vault-name $KvName --name "COSMOSDB-CRM-KEY" --query value -o tsv
$CosmosDb       = az keyvault secret show --vault-name $KvName --name "COSMOSDB-CRM-DATABASE" --query value -o tsv
Write-Done "Cosmos DB: $CosmosEndpoint / $CosmosDb"

Write-Step "Getting AKS credentials (Cosmos DB is behind a private endpoint)"
$AksName = az aks list --resource-group $ResourceGroup --query "[0].name" -o tsv
if (-not $AksName) { throw "No AKS cluster found in $ResourceGroup" }
az aks get-credentials --resource-group $ResourceGroup --name $AksName --overwrite-existing | Out-Null
Write-Done "AKS: $AksName"

Write-Step "Publishing seed-data tool for Linux"
$SeedDataDir = Join-Path (Split-Path $ScriptDir) "src" "seed-data"
$PublishDir   = Join-Path $SeedDataDir "bin" "publish"
Push-Location $SeedDataDir
try {
    dotnet publish -c Release -r linux-x64 --self-contained -o $PublishDir 2>&1 | Out-Null
    if ($LASTEXITCODE -ne 0) { throw "dotnet publish failed" }
    Write-Done "Published to $PublishDir"
} finally {
    Pop-Location
}

Write-Step "Running seed-data inside AKS cluster"
$K8sNamespace = "contoso"
$PodName = "seed-data-runner"
$CrmDataDir = Join-Path (Split-Path $ScriptDir) "data" "contoso-crm"

# Create temporary pod
kubectl run $PodName --image=mcr.microsoft.com/dotnet/runtime-deps:9.0 --restart=Never --namespace=$K8sNamespace --command -- sleep 600 2>&1 | Out-Null
kubectl wait --for=condition=Ready pod/$PodName --namespace=$K8sNamespace --timeout=120s 2>&1 | Out-Null
Write-Done "Pod $PodName ready"

try {
    # Copy published app and CRM data
    kubectl exec $PodName --namespace=$K8sNamespace -- mkdir -p /app /data/contoso-crm 2>&1 | Out-Null
    kubectl cp $PublishDir "${K8sNamespace}/${PodName}:/app" 2>&1 | Out-Null
    kubectl cp $CrmDataDir "${K8sNamespace}/${PodName}:/data/contoso-crm" 2>&1 | Out-Null
    kubectl exec $PodName --namespace=$K8sNamespace -- chmod +x /app/seed-data 2>&1 | Out-Null

    # Run seed-data with Cosmos DB connection
    kubectl exec $PodName --namespace=$K8sNamespace -- `
        /bin/sh -c "COSMOSDB_CRM_ENDPOINT='$CosmosEndpoint' COSMOSDB_CRM_KEY='$CosmosKey' COSMOSDB_CRM_DATABASE='$CosmosDb' CRM_DATA_PATH='/data/contoso-crm' /app/seed-data"
    if ($LASTEXITCODE -ne 0) { throw "seed-data failed" }
    Write-Done "CRM data seeded"
} finally {
    kubectl delete pod $PodName --namespace=$K8sNamespace --force --grace-period=0 2>&1 | Out-Null
}

Write-PhaseSummary -Number 6 -NextPhase "Phase 7 — Link Entra users to Customers" -Items ([ordered]@{
    "Status" = "CRM data seeded"
})

# ═══════════════════════════════════════════════════════════════════════════════
# PHASE 7 — Link Entra user object IDs to Customers
# ═══════════════════════════════════════════════════════════════════════════════

Write-Phase -Number 7 -Title "Link Entra users to Customers"

Write-Step "Reading Entra object IDs from Key Vault"

$CustomerMapping = @(
    @{ CustomerId = "101"; SecretName = "CUSTOMER-EMMA-ENTRA-OID";  Name = "Emma Wilson" }
    @{ CustomerId = "102"; SecretName = "CUSTOMER-JAMES-ENTRA-OID"; Name = "James Chen" }
    @{ CustomerId = "103"; SecretName = "CUSTOMER-SARAH-ENTRA-OID"; Name = "Sarah Miller" }
    @{ CustomerId = "104"; SecretName = "CUSTOMER-DAVID-ENTRA-OID"; Name = "David Park" }
    @{ CustomerId = "105"; SecretName = "CUSTOMER-LISA-ENTRA-OID";  Name = "Lisa Torres" }
)

Write-Step "Building Entra mapping and updating Cosmos DB via seed-data tool"
$EntraPairs = @()
foreach ($mapping in $CustomerMapping) {
    $oid = az keyvault secret show --vault-name $KvName --name $mapping.SecretName --query value -o tsv
    if ($oid) {
        $EntraPairs += "$($mapping.CustomerId)=$oid"
    } else {
        Write-Host "    ⚠ Could not read $($mapping.SecretName) from Key Vault" -ForegroundColor Yellow
    }
}
$EntraMapping = $EntraPairs -join ";"

# Reuse the seed-data pod pattern to run entra linking inside the cluster
$PodName7 = "entra-linker"
kubectl run $PodName7 --image=mcr.microsoft.com/dotnet/runtime-deps:9.0 --restart=Never --namespace=$K8sNamespace --command -- sleep 300 2>&1 | Out-Null
kubectl wait --for=condition=Ready pod/$PodName7 --namespace=$K8sNamespace --timeout=120s 2>&1 | Out-Null

try {
    kubectl exec $PodName7 --namespace=$K8sNamespace -- mkdir -p /app 2>&1 | Out-Null
    kubectl cp $PublishDir "${K8sNamespace}/${PodName7}:/app" 2>&1 | Out-Null
    kubectl exec $PodName7 --namespace=$K8sNamespace -- chmod +x /app/seed-data 2>&1 | Out-Null

    kubectl exec $PodName7 --namespace=$K8sNamespace -- `
        /bin/sh -c "COSMOSDB_CRM_ENDPOINT='$CosmosEndpoint' COSMOSDB_CRM_KEY='$CosmosKey' COSMOSDB_CRM_DATABASE='$CosmosDb' CRM_DATA_PATH='/dev/null' ENTRA_MAPPING='$EntraMapping' /app/seed-data"
    if ($LASTEXITCODE -ne 0) { throw "entra linking failed" }
    Write-Done "Entra users linked to Customers"
} finally {
    kubectl delete pod $PodName7 --namespace=$K8sNamespace --force --grace-period=0 2>&1 | Out-Null
}

# ── Read Key Vault URI ────────────────────────────────────────────────────────
$KeyVaultUri = (az keyvault show --name $KvName --query properties.vaultUri -o tsv 2>$null)

# ── Final summary ────────────────────────────────────────────────────────────
Write-Host ""
Write-Host "  ╔═══════════════════════════════════════════════════════╗" -ForegroundColor Green
Write-Host "  ║  Deployment Complete!                                 ║" -ForegroundColor Green
Write-Host "  ╠═══════════════════════════════════════════════════════╣" -ForegroundColor Green
Write-Host "  ║" -ForegroundColor Green -NoNewLine; Write-Host "  Environment:    $Environment"
Write-Host "  ║" -ForegroundColor Green -NoNewLine; Write-Host "  Resource group: $ResourceGroup"
Write-Host "  ║" -ForegroundColor Green -NoNewLine; Write-Host "  Location:       $Location"
if ($KeyVaultUri) {
    Write-Host "  ║" -ForegroundColor Green -NoNewLine; Write-Host "  Key Vault URI:  $KeyVaultUri"
}
Write-Host "  ║" -ForegroundColor Green
Write-Host "  ║  Next steps:                                          " -ForegroundColor Green
Write-Host "  ║    1. cd src/config-sync                               " -ForegroundColor Green
Write-Host "  ║    2. dotnet run -- $KeyVaultUri" -ForegroundColor Green
Write-Host "  ║    3. cd ../simple-agent && dotnet run                 " -ForegroundColor Green
Write-Host "  ╚═══════════════════════════════════════════════════════╝" -ForegroundColor Green
Write-Host ""

} finally {
    # ═══════════════════════════════════════════════════════════════════════════
    # ALWAYS: Remove deployer IP from all firewalls + lock state storage
    # This block runs even if the deploy fails or is interrupted.
    # ═══════════════════════════════════════════════════════════════════════════
    Remove-DeployerFirewallRules -ResourceGroup $ResourceGroup -DeployerIp $DeployerIp

    Write-Step "Removing deployer IP from $StorageAccount firewall"
    az storage account network-rule remove --account-name $StorageAccount --resource-group $ResourceGroup --ip-address $DeployerIp 2>$null | Out-Null
    Write-Done "Deployer IP removed from $StorageAccount"
}
