#!/usr/bin/env pwsh
#Requires -Version 7.0
<#
.SYNOPSIS
    Deploy infrastructure for the .NET Agent Framework workshop (Lab 1).

.DESCRIPTION
    Mirrors the CI/CD workflow: unlocks state storage, runs terraform
    init/validate/plan/apply, then shows next steps.

    Reads resource group / storage account names from the terraform.tfvars
    and backend.hcl generated by init.ps1.

.EXAMPLE
    ./deploy.ps1
#>

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

$ScriptDir    = $PSScriptRoot
$TerraformDir = "$ScriptDir\terraform"

# ── Helpers ──────────────────────────────────────────────────────────────────
function Write-Banner {
    Write-Host ""
    Write-Host "  ╔═══════════════════════════════════════════════════════╗" -ForegroundColor DarkCyan
    Write-Host "  ║                                                       ║" -ForegroundColor DarkCyan
    Write-Host "  ║   .NET Agent Framework — Lab 1 Deploy                 ║" -ForegroundColor DarkCyan
    Write-Host "  ║                                                       ║" -ForegroundColor DarkCyan
    Write-Host "  ║   This script deploys all Azure infrastructure:       ║" -ForegroundColor DarkCyan
    Write-Host "  ║     1. Unlock state storage                           ║" -ForegroundColor DarkCyan
    Write-Host "  ║     2. terraform init                                 ║" -ForegroundColor DarkCyan
    Write-Host "  ║     3. terraform validate                             ║" -ForegroundColor DarkCyan
    Write-Host "  ║     4. terraform plan                                 ║" -ForegroundColor DarkCyan
    Write-Host "  ║     5. terraform apply                                ║" -ForegroundColor DarkCyan
    Write-Host "  ║                                                       ║" -ForegroundColor DarkCyan
    Write-Host "  ╚═══════════════════════════════════════════════════════╝" -ForegroundColor DarkCyan
    Write-Host ""
}

function Write-Phase {
    param([int]$Number, [string]$Title)
    Write-Host ""
    Write-Host "  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━" -ForegroundColor DarkGray
    Write-Host "  Phase $Number — $Title" -ForegroundColor Cyan
    Write-Host "  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━" -ForegroundColor DarkGray
}

function Write-Step  { param([string]$Message) Write-Host "  → $Message" -ForegroundColor White }
function Write-Done  { param([string]$Message) Write-Host "    ✓ $Message" -ForegroundColor Green }

function Write-PhaseSummary {
    param([int]$Number, [hashtable]$Items, [string]$NextPhase)
    Write-Host ""
    Write-Host "    ┌ Phase $Number complete ─────────────────────────────────┐" -ForegroundColor Green
    foreach ($kv in $Items.GetEnumerator()) {
        Write-Host "    │  $($kv.Key): " -ForegroundColor Green -NoNewLine
        Write-Host "$($kv.Value)"
    }
    Write-Host "    └─────────────────────────────────────────────────────┘" -ForegroundColor Green
    if ($NextPhase) {
        Write-Host "    Next: " -NoNewLine -ForegroundColor DarkGray
        Write-Host "$NextPhase" -ForegroundColor Cyan
    }
    $response = Read-Host "    Continue? (Y/n)"
    if ($response -eq 'n' -or $response -eq 'N') {
        Write-Host "    Stopped by user." -ForegroundColor Yellow
        exit 0
    }
}

function Read-HclValue {
    param([string]$FilePath, [string]$Key)
    $line = Get-Content $FilePath | Where-Object { $_ -match "^\s*$Key\s*=" } | Select-Object -First 1
    if ($line -match '=\s*"([^"]*)"') { return $Matches[1] }
    return $null
}

# ── Read config ──────────────────────────────────────────────────────────────

$TfVarsFile  = "$TerraformDir\terraform.tfvars"
$BackendFile = "$TerraformDir\backend.hcl"

if (-not (Test-Path $TfVarsFile))  { throw "terraform.tfvars not found — run init.ps1 first." }
if (-not (Test-Path $BackendFile)) { throw "backend.hcl not found — run init.ps1 first." }

$ResourceGroup  = Read-HclValue -FilePath $TfVarsFile -Key "resource_group_name"
$Environment    = Read-HclValue -FilePath $TfVarsFile -Key "environment"
$Location       = Read-HclValue -FilePath $TfVarsFile -Key "location"
$StorageAccount = Read-HclValue -FilePath $BackendFile -Key "storage_account_name"

if (-not $ResourceGroup -or -not $StorageAccount -or -not $Environment) {
    throw "Could not read required values from config files. Re-run init.ps1."
}

Write-Banner

Write-Host "    Environment:     " -NoNewLine; Write-Host "$Environment" -ForegroundColor Cyan
Write-Host "    Resource group:  " -NoNewLine; Write-Host "$ResourceGroup" -ForegroundColor Cyan
Write-Host "    Storage account: " -NoNewLine; Write-Host "$StorageAccount" -ForegroundColor Cyan
Write-Host "    Location:        " -NoNewLine; Write-Host "$Location" -ForegroundColor Cyan
Write-Host ""

# ═══════════════════════════════════════════════════════════════════════════════
# PHASE 1 — Unlock state storage
# ═══════════════════════════════════════════════════════════════════════════════

Write-Phase -Number 1 -Title "Unlock state storage"

Write-Step "Enabling public access on $StorageAccount"

az storage account update `
    --name $StorageAccount `
    --resource-group $ResourceGroup `
    --public-network-access Enabled | Out-Null

Write-Done "Public access enabled on $StorageAccount"

Write-PhaseSummary -Number 1 -NextPhase "Phase 2 — terraform init (configure backend)" -Items ([ordered]@{
    "Storage account" = $StorageAccount
    "Public access"   = "Enabled"
})

# ═══════════════════════════════════════════════════════════════════════════════
# PHASE 2 — terraform init
# ═══════════════════════════════════════════════════════════════════════════════

Write-Phase -Number 2 -Title "terraform init"

Write-Step "Initializing Terraform with backend config"

Push-Location $TerraformDir
try {
    terraform --% init -reconfigure -backend-config=backend.hcl
    if ($LASTEXITCODE -ne 0) { throw "terraform init failed" }
    Write-Done "Terraform initialized"
} finally {
    Pop-Location
}

Write-PhaseSummary -Number 2 -NextPhase "Phase 3 — terraform validate (check configuration syntax)" -Items ([ordered]@{
    "Backend" = "azurerm ($StorageAccount/tfstate/$Environment.tfstate)"
    "Status"  = "Initialized"
})

# ═══════════════════════════════════════════════════════════════════════════════
# PHASE 3 — terraform validate
# ═══════════════════════════════════════════════════════════════════════════════

Write-Phase -Number 3 -Title "terraform validate"

Write-Step "Validating Terraform configuration"

Push-Location $TerraformDir
try {
    terraform validate
    if ($LASTEXITCODE -ne 0) { throw "terraform validate failed — fix errors above and re-run" }
    Write-Done "Configuration is valid"
} finally {
    Pop-Location
}

Write-PhaseSummary -Number 3 -NextPhase "Phase 4 — terraform plan (preview infrastructure changes)" -Items ([ordered]@{
    "Status" = "Valid"
})

# ═══════════════════════════════════════════════════════════════════════════════
# PHASE 4 — terraform plan
# ═══════════════════════════════════════════════════════════════════════════════

Write-Phase -Number 4 -Title "terraform plan"

Write-Step "Planning infrastructure changes"

Push-Location $TerraformDir
try {
    terraform --% plan -var-file="terraform.tfvars" -out="tfplan"
    if ($LASTEXITCODE -ne 0) { throw "terraform plan failed" }
    Write-Done "Plan saved to tfplan"
} finally {
    Pop-Location
}

Write-PhaseSummary -Number 4 -NextPhase "Phase 5 — terraform apply (provision all resources + seed data)" -Items ([ordered]@{
    "Plan file" = "tfplan"
    "Status"    = "Ready to apply"
})

# ═══════════════════════════════════════════════════════════════════════════════
# PHASE 5 — terraform apply
# ═══════════════════════════════════════════════════════════════════════════════

Write-Phase -Number 5 -Title "terraform apply"

Write-Step "Applying infrastructure changes"
Write-Host "    Resources: AI Foundry, SQL, Cosmos DB, AI Search, AKS, ACR, Key Vault, Storage" -ForegroundColor DarkGray
Write-Host ""

Push-Location $TerraformDir
try {
    terraform apply "tfplan"
    if ($LASTEXITCODE -ne 0) { throw "terraform apply failed" }
    Write-Done "All resources deployed and data seeded"
} finally {
    Pop-Location
}

# ── Clean up ─────────────────────────────────────────────────────────────────
if (Test-Path "$TerraformDir\tfplan") {
    Remove-Item "$TerraformDir\tfplan" -Force
}

Push-Location $TerraformDir
try {
    $KeyVaultUri = terraform output -raw keyvault_uri 2>$null
} finally {
    Pop-Location
}

# ── Final summary ────────────────────────────────────────────────────────────
Write-Host ""
Write-Host "  ╔═══════════════════════════════════════════════════════╗" -ForegroundColor Green
Write-Host "  ║  Deployment Complete!                                 ║" -ForegroundColor Green
Write-Host "  ╠═══════════════════════════════════════════════════════╣" -ForegroundColor Green
Write-Host "  ║" -ForegroundColor Green -NoNewLine; Write-Host "  Environment:    $Environment"
Write-Host "  ║" -ForegroundColor Green -NoNewLine; Write-Host "  Resource group: $ResourceGroup"
Write-Host "  ║" -ForegroundColor Green -NoNewLine; Write-Host "  Location:       $Location"
if ($KeyVaultUri) {
    Write-Host "  ║" -ForegroundColor Green -NoNewLine; Write-Host "  Key Vault URI:  $KeyVaultUri"
}
Write-Host "  ║" -ForegroundColor Green
Write-Host "  ║  Next steps:                                          " -ForegroundColor Green
Write-Host "  ║    1. cd src/config-sync                               " -ForegroundColor Green
Write-Host "  ║    2. dotnet run -- $KeyVaultUri" -ForegroundColor Green
Write-Host "  ║    3. cd ../simple-agent && dotnet run                 " -ForegroundColor Green
Write-Host "  ╚═══════════════════════════════════════════════════════╝" -ForegroundColor Green
Write-Host ""
