var builder = DistributedApplication.CreateBuilder(args);

// The AppHost is exclusively the LOCAL orchestrator. Force every child to load
// `appsettings.Local.json` (generated by `infra/setup-local.{ps1,sh}` with the
// Foundry endpoint and `DataMode=InMemory`) regardless of the AppHost's own
// environment. Without this override Aspire would propagate the AppHost's
// `ASPNETCORE_ENVIRONMENT=Development`, causing children to load
// `appsettings.Development.json` (which contains Azure endpoints from CI/CD)
// and fail to start in InMemory mode.
const string ChildEnvironment = "Local";

static IResourceBuilder<ProjectResource> AsLocal(IResourceBuilder<ProjectResource> project) =>
    project
        .WithEnvironment("ASPNETCORE_ENVIRONMENT", ChildEnvironment)
        .WithEnvironment("DOTNET_ENVIRONMENT", ChildEnvironment)
        // Restrict DefaultAzureCredential to dev-only credential sources
        // (Azure CLI, VS, IntelliJ, Azure Developer CLI). Without this every
        // service spends ~20 ms probing IMDS on 169.254.169.254 (which only
        // exists inside Azure) before falling back, polluting traces with
        // bogus `connection_error` spans.
        .WithEnvironment("AZURE_TOKEN_CREDENTIALS", "dev");

var crmApi = AsLocal(builder.AddProject<Projects.Contoso_CrmApi>("crm-api"))
    .WithHttpEndpoint(port: 5001, name: "http");

var crmMcp = AsLocal(builder.AddProject<Projects.Contoso_CrmMcp>("crm-mcp"))
    .WithHttpEndpoint(port: 5002, name: "http")
    .WithReference(crmApi);

var knowledgeMcp = AsLocal(builder.AddProject<Projects.Contoso_KnowledgeMcp>("knowledge-mcp"))
    .WithHttpEndpoint(port: 5003, name: "http");

var crmAgent = AsLocal(builder.AddProject<Projects.Contoso_CrmAgent>("crm-agent"))
    .WithHttpEndpoint(port: 5004, name: "http")
    .WithReference(crmMcp)
    .WithReference(knowledgeMcp);

var productAgent = AsLocal(builder.AddProject<Projects.Contoso_ProductAgent>("product-agent"))
    .WithHttpEndpoint(port: 5005, name: "http")
    .WithReference(crmMcp)
    .WithReference(knowledgeMcp);

var orchestratorAgent = AsLocal(builder.AddProject<Projects.Contoso_OrchestratorAgent>("orchestrator-agent"))
    .WithHttpEndpoint(port: 5006, name: "http")
    .WithReference(crmAgent)
    .WithReference(productAgent);

// Refund-risk workflow service (Lab 3). Owns the fan-out / fan-in /
// human-in-the-loop graph for refund alerts. Pulls findings from CRM +
// knowledge MCP backends; the operator dashboard lives in Blazor and
// posts decisions back through the BFF.
var fraudWorkflow = AsLocal(builder.AddProject<Projects.Contoso_FraudWorkflow>("fraud-workflow"))
    .WithHttpEndpoint(port: 5010, name: "http")
    .WithReference(crmMcp)
    .WithReference(knowledgeMcp);

// Wire the new outbound dependency from CRM API → fraud-workflow.
// When a customer creates a `category=return` ticket the CRM API fans
// the event out as a refund alert so the fraud workflow runs against
// REAL customer activity (the dev “Simulate alert” button on the
// Operations page is now an alternative trigger, not the only one).
crmApi.WithReference(fraudWorkflow);

var bffApi = AsLocal(builder.AddProject<Projects.Contoso_BffApi>("bff-api"))
    .WithHttpEndpoint(port: 5007, name: "http")
    .WithReference(crmApi)
    .WithReference(orchestratorAgent)
    .WithReference(fraudWorkflow);

AsLocal(builder.AddProject<Projects.Contoso_BlazorUi>("blazor-ui"))
    .WithHttpEndpoint(port: 5008, name: "http")
    .WithReference(bffApi);

builder.Build().Run();
