var builder = DistributedApplication.CreateBuilder(args);

// The AppHost is exclusively the LOCAL orchestrator. Force every child to load
// `appsettings.Local.json` (generated by `infra/setup-local.{ps1,sh}` with the
// Foundry endpoint and `DataMode=InMemory`) regardless of the AppHost's own
// environment. Without this override Aspire would propagate the AppHost's
// `ASPNETCORE_ENVIRONMENT=Development`, causing children to load
// `appsettings.Development.json` (which contains Azure endpoints from CI/CD)
// and fail to start in InMemory mode.
const string ChildEnvironment = "Local";

static IResourceBuilder<ProjectResource> AsLocal(IResourceBuilder<ProjectResource> project) =>
    project
        .WithEnvironment("ASPNETCORE_ENVIRONMENT", ChildEnvironment)
        .WithEnvironment("DOTNET_ENVIRONMENT", ChildEnvironment);

var crmApi = AsLocal(builder.AddProject<Projects.Contoso_CrmApi>("crm-api"))
    .WithHttpEndpoint(port: 5001, name: "http");

var crmMcp = AsLocal(builder.AddProject<Projects.Contoso_CrmMcp>("crm-mcp"))
    .WithHttpEndpoint(port: 5002, name: "http")
    .WithReference(crmApi);

var knowledgeMcp = AsLocal(builder.AddProject<Projects.Contoso_KnowledgeMcp>("knowledge-mcp"))
    .WithHttpEndpoint(port: 5003, name: "http");

var crmAgent = AsLocal(builder.AddProject<Projects.Contoso_CrmAgent>("crm-agent"))
    .WithHttpEndpoint(port: 5004, name: "http")
    .WithReference(crmMcp)
    .WithReference(knowledgeMcp);

var productAgent = AsLocal(builder.AddProject<Projects.Contoso_ProductAgent>("product-agent"))
    .WithHttpEndpoint(port: 5005, name: "http")
    .WithReference(crmMcp)
    .WithReference(knowledgeMcp);

var orchestratorAgent = AsLocal(builder.AddProject<Projects.Contoso_OrchestratorAgent>("orchestrator-agent"))
    .WithHttpEndpoint(port: 5006, name: "http")
    .WithReference(crmAgent)
    .WithReference(productAgent);

var bffApi = AsLocal(builder.AddProject<Projects.Contoso_BffApi>("bff-api"))
    .WithHttpEndpoint(port: 5007, name: "http")
    .WithReference(crmApi)
    .WithReference(orchestratorAgent);

AsLocal(builder.AddProject<Projects.Contoso_BlazorUi>("blazor-ui"))
    .WithHttpEndpoint(port: 5008, name: "http")
    .WithReference(bffApi);

builder.Build().Run();
