output "id" {
  description = "App Gateway for Containers resource ID"
  value       = azurerm_application_load_balancer.this.id
}

output "name" {
  description = "App Gateway for Containers name"
  value       = azurerm_application_load_balancer.this.name
}

output "frontend_id" {
  description = "AGC Frontend resource ID"
  value       = azurerm_application_load_balancer_frontend.this.id
}

output "frontend_fqdn" {
  description = "AGC Frontend FQDN (auto-generated by Azure)"
  value       = azurerm_application_load_balancer_frontend.this.fully_qualified_domain_name
}
