using Azure.AI.Projects;
using Azure.Identity;
using Microsoft.Agents.AI;
using Microsoft.Extensions.Configuration;

// simple-agent is the smallest local connectivity sample for Microsoft Agent Framework.
// It reads appsettings.Local.json generated by infra/setup-local.{ps1,sh}, authenticates
// with DefaultAzureCredential, and runs one prompt against the configured Foundry model.

var environmentName =
    Environment.GetEnvironmentVariable("DOTNET_ENVIRONMENT") ??
    Environment.GetEnvironmentVariable("ASPNETCORE_ENVIRONMENT") ??
    "Local";

var configuration = new ConfigurationBuilder()
    .AddJsonFile($"appsettings.{environmentName}.json", optional: true)
    .AddEnvironmentVariables()
    .Build();

var endpoint = configuration["Foundry:ProjectEndpoint"]
    ?? throw new InvalidOperationException("Foundry:ProjectEndpoint is not set.");
var deploymentName = configuration["Foundry:DeploymentName"]
    ?? throw new InvalidOperationException("Foundry:DeploymentName is not set.");
var tenantId = configuration["AzureAd:TenantId"];

Console.WriteLine($"Using AI Foundry project endpoint: {endpoint}");
Console.WriteLine($"Model deployment:                  {deploymentName}");
Console.WriteLine($"Auth mode:                         DefaultAzureCredential (Tenant: {(string.IsNullOrEmpty(tenantId) ? "default" : tenantId)})");

var credential = string.IsNullOrEmpty(tenantId)
    ? new DefaultAzureCredential()
    : new DefaultAzureCredential(new DefaultAzureCredentialOptions { TenantId = tenantId });

AIAgent agent = new AIProjectClient(new Uri(endpoint), credential)
    .AsAIAgent(
        model: deploymentName,
        instructions: "You are a helpful and funny assistant who tells short jokes.",
        name: "Joker");

var result = await agent.RunAsync("Tell me a joke about the cloud.");
Console.WriteLine($"\nAgent response:\n {result}");
