name: Terraform Plan, Approve, Apply, Seed Data
on: 
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select environment'
        required: true
        default: dev
        type: choice
        options:
          - dev
          - staging
          - production

permissions:
  id-token: write
  contents: read
  issues: write

jobs:

  terraform-plan:
    name: Terraform Plan
    uses: ./.github/workflows/terraform-plan.yaml
    with:
      environment: ${{ inputs.environment }}
    secrets:
      azureClientId: ${{ secrets.AZURE_CLIENT_ID }}
      azureTenantId: ${{ secrets.AZURE_TENANT_ID }}
      azureSubscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

  
  manual-approval:
    name: Manual Approval
    needs: [terraform-plan]
    runs-on: ubuntu-latest
    steps:
      - uses: trstringer/manual-approval@v1
        with:
          secret: ${{ github.TOKEN }}
          approvers: ${{ github.repository_owner }}
          minimum-approvals: 1
          issue-title: "Approve deployment to production"
          issue-body: "Please approve or deny the deployment."
          fail-on-denial: true

  purge-soft-deleted:
    name: Purge Soft-Deleted Resources
    needs: [manual-approval]
    uses: ./.github/workflows/purge-soft-deleted.yaml
    with:
      environment: ${{ inputs.environment }}
    secrets:
      azureClientId: ${{ secrets.AZURE_CLIENT_ID }}
      azureTenantId: ${{ secrets.AZURE_TENANT_ID }}
      azureSubscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

  terraform-apply:
    name: Terraform Apply
    needs: [purge-soft-deleted]
    uses: ./.github/workflows/terraform-apply.yaml
    with:
      environment: ${{ inputs.environment }}
    secrets:
      azureClientId: ${{ secrets.AZURE_CLIENT_ID }}
      azureTenantId: ${{ secrets.AZURE_TENANT_ID }}
      azureSubscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

  seed-data:
    name: Seed CRM Data
    needs: [terraform-apply]
    uses: ./.github/workflows/seed-data.yaml
    with:
      environment: ${{ inputs.environment }}
    secrets:
      azureClientId: ${{ secrets.AZURE_CLIENT_ID }}
      azureTenantId: ${{ secrets.AZURE_TENANT_ID }}
      azureSubscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}